name: Spicetify GUI Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-xinerama0

      - name: Build
        run: |
          # Start xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 -extension RANDR -ac &
        
       - name: Test
         run: |
          # Run the Python script using xvfb-run 
          xvfb-run python app.py

